export const t = {
  common: {
    toggleTheme: "Переключить тему",
    loading: "Загрузка...",
  },
  auth: {
    welcomeBack: "С возвращением",
    loginToContinue: "Войдите, чтобы продолжить",
    email: "Email",
    password: "Пароль",
    signIn: "Войти",
    signUp: "Зарегистрироваться",
    enterEmail: "Введите ваш email",
    enterPassword: "Введите ваш пароль",
    successLogin: "Вход выполнен успешно!",
    successLogout: "Выход выполнен успешно!",
    sessionExpired: "Сессия истекла. Пожалуйста, войдите снова",
    invalidAuth: "Получены неверные данные аутентификации",
    loginFailed: "Ошибка входа",
    createAccount: "Создать аккаунт",
    fillInformation: "Заполните информацию для регистрации",
    firstName: "Имя",
    lastName: "Фамилия",
    patronymic: "Отчество",
    enterFirstName: "Введите имя",
    enterLastName: "Введите фамилию",
    enterPatronymic: "Введите отчество",
    signupFailed: "Ошибка при регистрации",
    validation: {
      emailRequired: "Email обязателен",
      emailInvalid: "Неверный формат email",
      passwordRequired: "Пароль обязателен",
      passwordMin: "Пароль должен содержать минимум {{min}} символов",
      firstNameRequired: "Имя обязательно",
      lastNameRequired: "Фамилия обязательна",
      patronymicRequired: "Отчество обязательно",
    },
    noAccount: "Нет аккаунта?",
    haveAccount: "Уже есть аккаунт?",
    submit: "Отправить",
  }
}; 